"""tabela produto

Revision ID: 091cf416f295
Revises: 7e4a39f36bca
Create Date: 2026-07-03 16:23:25.585056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '091cf416f295'
down_revision: Union[str, Sequence[str], None] = '7e4a39f36bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('codigo_barras', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lancamento', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_produto_categoria'), 'produto', ['categoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_categoria'), table_name='produto')
    op.drop_table('produto')
    # ### end Alembic commands ###
