"""reset pwd table

Revision ID: 9595f4caa44e
Revises: 8ab9a29ca679
Create Date: 2026-03-23 13:25:20.423760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9595f4caa44e'
down_revision: Union[str, Sequence[str], None] = '8ab9a29ca679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordreset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordreset_email'), 'passwordreset', ['email'], unique=False)
    op.create_index(op.f('ix_passwordreset_token'), 'passwordreset', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwordreset_token'), table_name='passwordreset')
    op.drop_index(op.f('ix_passwordreset_email'), table_name='passwordreset')
    op.drop_table('passwordreset')
    # ### end Alembic commands ###
