"""empty message

Revision ID: f43c5e5a5047
Revises: 252dad475cb5
Create Date: 2025-10-15 08:19:48.556924

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f43c5e5a5047"
down_revision: str | Sequence[str] | None = "252dad475cb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "user",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
